-- Remplissage des constellations
insert into Constellations (id, properEngName, properFrName, latinName, abbreviation)
values
(1,		'Aquila', 				'Aigle', 						'Aquila', 				'Aql'),
(2,		'Andromeda', 			'Andromède', 					'Andromeda', 			'And'),
(3,		'Ara', 					'Autel', 						'Ara', 					'Ara'),
(4,		'Libra', 				'Balance', 						'Libra', 				'Lib'),
(5,		'Cetus', 				'Baleine', 						'Cetus', 				'Cet'),
(6,		'Aries', 				'Bélier', 						'Aries', 				'Ari'),
(7,		'Pyxis', 				'Boussole', 					'Pyxis', 				'Pyx'),
(8,		'Bootes', 				'Bouvier', 						'Bootes', 				'Boo'),
(9,		'Caelum', 				'Burin', 						'Caelum', 				'Cae'),
(10,	'Chamaeleon', 			'Caméléon', 					'Chamaeleon', 			'Cha'),
(11,	'Cancer', 				'Cancer', 						'Cancer', 				'Cnc'),
(12,	'Capricornus', 			'Capricorne', 					'Capricornus', 			'Cap'),
(13,	'Carina', 				'Carène', 						'Carina', 				'Car'),
(14,	'Cassiopeia', 			'Cassiopée', 					'Cassiopeia', 			'Cas'),
(15,	'Centaurus', 			'Centaure', 					'Centaurus', 			'Cen'),
(16,	'Cepheus', 				'Céphée', 						'Cepheus', 				'Cep'),
(17,	'Coma Berenices', 		'Chevelure de Bérénice', 		'Coma Berenices', 		'Com'),
(18,	'Canes Venatici', 		'Chiens de chasse', 			'Canes Venatici', 		'CVn'),
(19,	'Auriga', 				'Cocher', 						'Auriga', 				'Aur'),
(20,	'Colomba', 				'Colombe', 						'Colomba', 				'Col'),
(21,	'Circinus', 			'Compas', 						'Circinus', 			'Cir'),
(22,	'Corvus', 				'Corbeau', 						'Corvus', 				'Crv'),
(23,	'Crater', 				'Coupe', 						'Crater', 				'Crt'),
(24,	'Corona Australis', 	'Couronne australe', 			'Corona Australis', 	'CrA'),
(25,	'Corona Borealis', 		'Couronne Boréale', 			'Corona Borealis', 		'CrB'),
(26,	'Crux', 				'Croix du sud', 				'Crux', 				'Cru'),
(27,	'Cygnus', 				'Cygne', 						'Cygnus', 				'Cyg'),
(28,	'Delphinus', 			'Dauphin', 						'Delphinus', 			'Del'),
(29,	'Dorado', 				'Dorade', 						'Dorado', 				'Dor'),
(30,	'Draco', 				'Dragon', 						'Draco', 				'Dra'),
(31,	'Scutum', 				'Ecu de Sobieski', 				'Scutum', 				'Sct'),
(32,	'Eridanus',				'Eridan', 						'Eridanus', 			'Eri'),
(33,	'Sagitta', 				'Flèche', 						'Sagitta', 				'Sge'),
(34,	'Fornax', 				'Fourneau', 					'Fornax', 				'For'),
(35,	'Gemini', 				'Gémeaux', 						'Gemini', 				'Gem'),
(36,	'Camelopardalis', 		'Girafe', 						'Camelopardalis', 		'Cam'),
(37,	'Canis Major', 			'Grand chien', 					'Canis Major', 			'CMa'),
(38,	'Ursa Major', 			'Grande Ourse', 				'Ursa Major', 			'UMa'),
(39,	'Grus', 				'Grue', 						'Grus', 				'Gru'),
(40,	'Hercules', 			'Hercule', 						'Hercules', 			'Her'),
(41,	'Horologium', 			'Horloge', 						'Horologium', 			'Hor'),
(42,	'Hydra',				'Hydre', 						'Hydra', 				'Hya'),
(43,	'Hydrus', 				'Hydre Mâle', 					'Hydrus', 				'Hyi'),
(44,	'Indus', 				'Indien', 						'Indus', 				'Ind'),
(45,	'Lacerta', 				'Lézard', 						'Lacerta', 				'Lac'),
(46,	'Monoceros', 			'Licorne', 						'Monoceros', 			'Mon'),
(47,	'Lepus', 				'Lièvre', 						'Lepus', 				'Lep'),
(48,	'Leo', 					'Lion', 						'Leo', 					'Leo'),
(49,	'Lupus', 				'Loup', 						'Lupus', 				'Lup'),
(50,	'Lynx',					'Lynx',							'Lynx',					'Lyn'),
(51, 	'Lyra',					'Lyre',							'Lyra',					'Lyr'),
(52,	'Antlia',				'Machine pneumatique',			'Antlia',				'Ant'),
(53,	'Microscopium',			'Microscope',					'Microscopium',     	'Mic'),
(54,	'Musca',				'Mouche',						'Musca',				'Mus'),
(55,	'Octans',				'Octant',						'Octans',				'Oct'),
(56,	'Apus',					'Oiseau de paradis',			'Apus',					'Aps'),
(57,	'Ophiuchus',			'Ophiuchus',					'Ophiuchus',			'Oph'),
(58,	'Orion',				'Orion',						'Orion',				'Ori'),
(59,	'Pavo',					'Paon',							'Pavo',					'Pav'),
(60,	'Pegasus',				'Pégase',						'Pegasus',				'Peg'),
(61,	'Pictor',				'Peintre',						'Pictor',				'Pic'),
(62,	'Perseus',				'Persée',						'Perseus',				'Per'),
(63,	'Equuleus',				'Petit Cheval',					'Equuleus',				'Equ'),
(64,	'Canis Minor',			'Petit Chien',					'Canis Minor',			'CMi'),
(65,	'Leo Minor',			'Petit Lion',					'Leo Minor',			'LMi'),
(66,	'Vulpecula',			'Petit Renard',					'Vulpecula',			'Vul'),
(67,	'Ursa Minor',			'Petite Ourse',					'Ursa Minor',			'UMi'),
(68,	'Phoenix',				'Phénix',						'Phoenix',				'Phe'),
(69,	'Piscis Austrinus',		'Poisson austral',				'Piscis Austrinus',		'PsA'),
(70,	'Volans',				'Poisson volant',				'Volans',				'Vol'),
(71,	'Pisces',				'Poissons',						'Pisces',				'Psc'),
(72,	'Puppis',				'Poupe',						'Puppis',				'Pup'),
(73,	'Norma',				'Règle',						'Norma',				'Nor'),
(74,	'Reticulum',			'Réticule',						'Reticulum',			'Ret'),
(75,	'Sagittarius',			'Sagittaire',					'Sagittarius',			'Sgr'),
(76,	'Scorpius',				'Scorpion',						'Scorpius',				'Sco'),
(77,	'Sculptor',				'Sculpteur',					'Sculptor',				'Scl'),
(78,	'Serpens',				'Serpent',						'Serpens',				'Ser'),
(79,	'Sextans',				'Sextant',						'Sextans',				'Sex'),
(80,	'Mensa',				'Table',						'Mensa',				'Men'),
(81,	'Taurus',				'Taureau',						'Taurus',				'Tau'),
(82,	'Telescopium',			'Télescope',					'Telescopium',			'Tel'),
(83,	'Tucana',				'Toucan',						'Tucana',				'Tuc'),
(84,	'Triangulum',			'Triangle',						'Triangulum',			'Tri'),
(85,	'Triangulum Australe',	'Triangle austral',				'Triangulum Australe',	'TrA'),
(86,	'Aquarius',				'Verseau',						'Aquarius',				'Aqr'),
(87,	'Virgo',				'Vierge',						'Virgo',				'Vir'),
(88,	'Vela',					'Voiles',						'Vela',					'Vel')